Update gradle.yml
mbeddr/build.publish.mps pull request #10
Opened 2023-07-24 14:35 UTC by arimer

gradle actions only executed on master and mps/** branches. Prohibits publication on PRs. Fixes failing re-publication on master after merge.

2023-07-24 14:41 UTC, alexanderpann requested changes
You have to test the `packageX` tasks on push. Every step excluding the publishing should still be tested when a PR is created.  They sometimes fail for new MPS versions.

2023-07-25 15:06 UTC, arimer commented on build.gradle
> +task testPackaging{
@alexanderpann what do you think about that idea? We could perform a "dry-run" of all packaging tasks to see if any of them breaks before trying to publish.

2023-07-25 15:57 UTC, alexanderpann commented on build.gradle
> +task testPackaging{
Yes, that is exactly what I was thinking.

2023-07-26 08:08 UTC, arimer commented
@alexanderpann I've re-structures our .yaml file a little and updated the description. Feel free to have a second look

2023-07-26 08:19 UTC, arimer commented on .github/workflows/gradle.yml
> +    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/mps/*')
@alexanderpann I think we need to try out if `startsWith(github.ref, 'refs/mps/*') `works as expected. Othwerwise we can just simplify the check to `startsWith(github.ref, 'refs/mps') `(withouht the `*`)

2023-07-26 09:41 UTC, alexanderpann commented on .github/workflows/gradle.yml
> +    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/mps/*')
`startsWith(github.ref, 'refs/mps/')` is probably also safe. Let's use your second approach or mine, should be good enough.

2023-07-27 08:09 UTC, alexanderpann approved these changes
Looks good.

2023-07-27 08:10 UTC, merged